# What do want?
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: mylocalstorage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 9Gi
---
# How do we want it implemented
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage
spec:
  storageClassName: mylocalstorage
  capacity:
    storage: 9Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/somenew/directory/structure/"
    type: DirectoryOrCreate

#when you implemente a pressitance volume mount you create in your local deviec storage 
#a volume of the data represnted in a working pod database 
#if the pods fails or deleted the pod data fatched the data from the volume moant 